defaults: &defaults
  working_directory: ~/workspace
  docker:
    - image: pasonpower/circleci-python:3

orbs:
  aws-ecr: circleci/aws-ecr@6.13.0

version: 2.1
jobs:
  check-test:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Lint
          command: |
            . venv/bin/activate
            # flake8 src/
            black -l 120 --check src/
      - run:
          name: Test
          command: |
            . venv/bin/activate
            pytest src
workflows:
  check-test-push-deploy:
    jobs:
      - check-test:
          filters:
            tags:
              only: /.*/
      - aws-ecr/build-and-push-image:
          # This needs to be configured for the build to work
          repo: etb/acumen-backup
          account-url: AWS_ECR_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          context: org-global
          create-repo: true
          region: AWS_DEFAULT_REGION
          dockerfile: Dockerfile
          path: .
          tag: '$CIRCLE_TAG,$CIRCLE_SHA1'
          requires:
            - check-test
          filters:
            tags:
              only: /^.*/
            branches:
              only:
                - master